"""
Country code to name mapping (ISO 3166-1 alpha-2 to full country names).
"""

COUNTRY_NAMES: dict[str, str] = {
    "US": "United States",
    "GB": "United Kingdom",
    "CA": "Canada",
    "AU": "Australia",
    "DE": "Germany",
    "FR": "France",
    "IT": "Italy",
    "ES": "Spain",
    "NL": "Netherlands",
    "BR": "Brazil",
    "IN": "India",
    "CN": "China",
    "JP": "Japan",
    "KR": "South Korea",
    "MX": "Mexico",
    "AR": "Argentina",
    "ZA": "South Africa",
    "NG": "Nigeria",
    "EG": "Egypt",
    "TR": "Turkey",
    "RU": "Russia",
    "PL": "Poland",
    "SE": "Sweden",
    "NO": "Norway",
    "DK": "Denmark",
    "FI": "Finland",
    "BE": "Belgium",
    "CH": "Switzerland",
    "AT": "Austria",
    "IE": "Ireland",
    "PT": "Portugal",
    "GR": "Greece",
    "CZ": "Czech Republic",
    "HU": "Hungary",
    "RO": "Romania",
    "UA": "Ukraine",
    "SA": "Saudi Arabia",
    "AE": "United Arab Emirates",
    "IL": "Israel",
    "TH": "Thailand",
    "VN": "Vietnam",
    "PH": "Philippines",
    "ID": "Indonesia",
    "MY": "Malaysia",
    "SG": "Singapore",
    "NZ": "New Zealand",
    "CL": "Chile",
    "CO": "Colombia",
    "PE": "Peru",
    "VE": "Venezuela",
    "PK": "Pakistan",
    "BD": "Bangladesh",
    "KE": "Kenya",
    "GH": "Ghana",
    "ET": "Ethiopia",
    "TZ": "Tanzania",
    "UG": "Uganda",
    "AO": "Angola",
    "DZ": "Algeria",
    "MA": "Morocco",
    "TN": "Tunisia",
    "LY": "Libya",
    "SD": "Sudan",
    "IQ": "Iraq",
    "IR": "Iran",
    "AF": "Afghanistan",
    "KZ": "Kazakhstan",
    "UZ": "Uzbekistan",
    "BY": "Belarus",
    "BG": "Bulgaria",
    "HR": "Croatia",
    "RS": "Serbia",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "LT": "Lithuania",
    "LV": "Latvia",
    "EE": "Estonia",
    "IS": "Iceland",
    "LU": "Luxembourg",
    "MT": "Malta",
    "CY": "Cyprus",
    "CR": "Costa Rica",
    "PA": "Panama",
    "GT": "Guatemala",
    "HN": "Honduras",
    "SV": "El Salvador",
    "NI": "Nicaragua",
    "DO": "Dominican Republic",
    "CU": "Cuba",
    "JM": "Jamaica",
    "TT": "Trinidad and Tobago",
    "BO": "Bolivia",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "EC": "Ecuador",
    "GY": "Guyana",
    "SR": "Suriname",
    "FJ": "Fiji",
    "PG": "Papua New Guinea",
    "NC": "New Caledonia",
    "PF": "French Polynesia",
    "WS": "Samoa",
    "TO": "Tonga",
    "VU": "Vanuatu",
    "SB": "Solomon Islands",
    "KI": "Kiribati",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "PW": "Palau",
    "FM": "Micronesia",
    "MH": "Marshall Islands",
    "AS": "American Samoa",
    "GU": "Guam",
    "MP": "Northern Mariana Islands",
    "VI": "U.S. Virgin Islands",
    "PR": "Puerto Rico",
    "BS": "Bahamas",
    "BB": "Barbados",
    "BZ": "Belize",
    "GD": "Grenada",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent and the Grenadines",
    "AG": "Antigua and Barbuda",
    "DM": "Dominica",
    "KN": "Saint Kitts and Nevis",
    "BT": "Bhutan",
    "MV": "Maldives",
    "LK": "Sri Lanka",
    "NP": "Nepal",
    "MM": "Myanmar",
    "KH": "Cambodia",
    "LA": "Laos",
    "BN": "Brunei",
    "TL": "Timor-Leste",
    "MN": "Mongolia",
    "KP": "North Korea",
    "TW": "Taiwan",
    "HK": "Hong Kong",
    "MO": "Macau",
    "KG": "Kyrgyzstan",
    "TJ": "Tajikistan",
    "TM": "Turkmenistan",
    "GE": "Georgia",
    "AM": "Armenia",
    "AZ": "Azerbaijan",
    "JO": "Jordan",
    "LB": "Lebanon",
    "SY": "Syria",
    "YE": "Yemen",
    "OM": "Oman",
    "QA": "Qatar",
    "BH": "Bahrain",
    "KW": "Kuwait",
    "PS": "Palestine",
    "CY": "Cyprus",
    "MD": "Moldova",
    "AL": "Albania",
    "MK": "North Macedonia",
    "BA": "Bosnia and Herzegovina",
    "ME": "Montenegro",
    "XK": "Kosovo",
    "AD": "Andorra",
    "LI": "Liechtenstein",
    "MC": "Monaco",
    "SM": "San Marino",
    "VA": "Vatican City",
    "GI": "Gibraltar",
    "FO": "Faroe Islands",
    "GL": "Greenland",
    "SJ": "Svalbard and Jan Mayen",
    "AX": "Åland Islands",
    "JE": "Jersey",
    "GG": "Guernsey",
    "IM": "Isle of Man",
    "IO": "British Indian Ocean Territory",
    "PN": "Pitcairn",
    "SH": "Saint Helena",
    "GS": "South Georgia and the South Sandwich Islands",
    "TF": "French Southern Territories",
    "HM": "Heard Island and McDonald Islands",
    "CC": "Cocos (Keeling) Islands",
    "CX": "Christmas Island",
    "NF": "Norfolk Island",
    "AQ": "Antarctica",
    "BV": "Bouvet Island",
    "EH": "Western Sahara",
    "GF": "French Guiana",
    "GP": "Guadeloupe",
    "MQ": "Martinique",
    "RE": "Réunion",
    "YT": "Mayotte",
    "PM": "Saint Pierre and Miquelon",
    "BL": "Saint Barthélemy",
    "MF": "Saint Martin",
    "CW": "Curaçao",
    "AW": "Aruba",
    "SX": "Sint Maarten",
    "BQ": "Caribbean Netherlands",
    "FK": "Falkland Islands",
    "GF": "French Guiana",
    "GY": "Guyana",
    "SR": "Suriname",
    "UY": "Uruguay",
    "PY": "Paraguay",
    "BO": "Bolivia",
    "EC": "Ecuador",
    "CO": "Colombia",
    "VE": "Venezuela",
    "PE": "Peru",
    "BR": "Brazil",
    "CL": "Chile",
    "AR": "Argentina",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "GY": "Guyana",
    "SR": "Suriname",
    "FK": "Falkland Islands",
    "GF": "French Guiana",
    "BQ": "Caribbean Netherlands",
    "SX": "Sint Maarten",
    "AW": "Aruba",
    "CW": "Curaçao",
    "MF": "Saint Martin",
    "BL": "Saint Barthélemy",
    "PM": "Saint Pierre and Miquelon",
    "YT": "Mayotte",
    "RE": "Réunion",
    "MQ": "Martinique",
    "GP": "Guadeloupe",
    "GF": "French Guiana",
    "EH": "Western Sahara",
    "BV": "Bouvet Island",
    "AQ": "Antarctica",
    "NF": "Norfolk Island",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "HM": "Heard Island and McDonald Islands",
    "TF": "French Southern Territories",
    "GS": "South Georgia and the South Sandwich Islands",
    "SH": "Saint Helena",
    "PN": "Pitcairn",
    "IO": "British Indian Ocean Territory",
    "IM": "Isle of Man",
    "GG": "Guernsey",
    "JE": "Jersey",
    "AX": "Åland Islands",
    "SJ": "Svalbard and Jan Mayen",
    "GL": "Greenland",
    "FO": "Faroe Islands",
    "GI": "Gibraltar",
    "VA": "Vatican City",
    "SM": "San Marino",
    "MC": "Monaco",
    "LI": "Liechtenstein",
    "AD": "Andorra",
    "XK": "Kosovo",
    "ME": "Montenegro",
    "BA": "Bosnia and Herzegovina",
    "MK": "North Macedonia",
    "AL": "Albania",
    "MD": "Moldova",
    "PS": "Palestine",
    "KW": "Kuwait",
    "BH": "Bahrain",
    "QA": "Qatar",
    "OM": "Oman",
    "YE": "Yemen",
    "SY": "Syria",
    "LB": "Lebanon",
    "JO": "Jordan",
    "AZ": "Azerbaijan",
    "AM": "Armenia",
    "GE": "Georgia",
    "TM": "Turkmenistan",
    "TJ": "Tajikistan",
    "KG": "Kyrgyzstan",
    "MO": "Macau",
    "HK": "Hong Kong",
    "TW": "Taiwan",
    "KP": "North Korea",
    "MN": "Mongolia",
    "TL": "Timor-Leste",
    "BN": "Brunei",
    "LA": "Laos",
    "KH": "Cambodia",
    "MM": "Myanmar",
    "NP": "Nepal",
    "LK": "Sri Lanka",
    "MV": "Maldives",
    "BT": "Bhutan",
    "KN": "Saint Kitts and Nevis",
    "DM": "Dominica",
    "AG": "Antigua and Barbuda",
    "VC": "Saint Vincent and the Grenadines",
    "LC": "Saint Lucia",
    "GD": "Grenada",
    "BZ": "Belize",
    "BB": "Barbados",
    "BS": "Bahamas",
    "PR": "Puerto Rico",
    "VI": "U.S. Virgin Islands",
    "MP": "Northern Mariana Islands",
    "GU": "Guam",
    "AS": "American Samoa",
    "MH": "Marshall Islands",
    "FM": "Micronesia",
    "PW": "Palau",
    "NR": "Nauru",
    "TV": "Tuvalu",
    "KI": "Kiribati",
    "SB": "Solomon Islands",
    "VU": "Vanuatu",
    "TO": "Tonga",
    "WS": "Samoa",
    "PF": "French Polynesia",
    "NC": "New Caledonia",
    "PG": "Papua New Guinea",
    "FJ": "Fiji",
    "SR": "Suriname",
    "GY": "Guyana",
    "EC": "Ecuador",
    "UY": "Uruguay",
    "PY": "Paraguay",
    "BO": "Bolivia",
    "TT": "Trinidad and Tobago",
    "JM": "Jamaica",
    "CU": "Cuba",
    "DO": "Dominican Republic",
    "NI": "Nicaragua",
    "SV": "El Salvador",
    "HN": "Honduras",
    "GT": "Guatemala",
    "PA": "Panama",
    "CR": "Costa Rica",
    "CY": "Cyprus",
    "MT": "Malta",
    "LU": "Luxembourg",
    "IS": "Iceland",
    "EE": "Estonia",
    "LV": "Latvia",
    "LT": "Lithuania",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "RS": "Serbia",
    "HR": "Croatia",
    "BG": "Bulgaria",
    "BY": "Belarus",
    "UZ": "Uzbekistan",
    "KZ": "Kazakhstan",
    "AF": "Afghanistan",
    "IR": "Iran",
    "IQ": "Iraq",
    "SD": "Sudan",
    "LY": "Libya",
    "TN": "Tunisia",
    "MA": "Morocco",
    "DZ": "Algeria",
    "AO": "Angola",
    "UG": "Uganda",
    "TZ": "Tanzania",
    "ET": "Ethiopia",
    "GH": "Ghana",
    "KE": "Kenya",
    "BD": "Bangladesh",
    "PK": "Pakistan",
    "VE": "Venezuela",
    "PE": "Peru",
    "CO": "Colombia",
    "CL": "Chile",
    "SG": "Singapore",
    "MY": "Malaysia",
    "ID": "Indonesia",
    "PH": "Philippines",
    "VN": "Vietnam",
    "TH": "Thailand",
    "IL": "Israel",
    "AE": "United Arab Emirates",
    "SA": "Saudi Arabia",
    "UA": "Ukraine",
    "RO": "Romania",
    "HU": "Hungary",
    "CZ": "Czech Republic",
    "GR": "Greece",
    "PT": "Portugal",
    "IE": "Ireland",
    "AT": "Austria",
    "CH": "Switzerland",
    "BE": "Belgium",
    "FI": "Finland",
    "DK": "Denmark",
    "NO": "Norway",
    "SE": "Sweden",
    "PL": "Poland",
    "RU": "Russia",
    "TR": "Turkey",
    "EG": "Egypt",
    "NG": "Nigeria",
    "ZA": "South Africa",
    "AR": "Argentina",
    "MX": "Mexico",
    "KR": "South Korea",
    "JP": "Japan",
    "CN": "China",
    "IN": "India",
    "BR": "Brazil",
    "NL": "Netherlands",
    "ES": "Spain",
    "IT": "Italy",
    "FR": "France",
    "DE": "Germany",
    "AU": "Australia",
    "CA": "Canada",
    "GB": "United Kingdom",
    "US": "United States",
}


def get_country_name(country_code: str | None) -> str:
    """Get full country name from ISO 3166-1 alpha-2 code. Returns code if not found."""
    if not country_code:
        return "Unknown"
    return COUNTRY_NAMES.get(country_code.upper(), country_code.upper())

